"""Generate the EU AI Act Art. 53(1)(d) training-data-summary template.

**Scope, stated plainly, checked at every change to this file:** Art. 53(1)(d)
of the EU AI Act requires providers of *general-purpose AI (GPAI) models* to
publish a "sufficiently detailed summary" of the content used to train the
model, using the template the European Commission's AI Office published on
2025-07-24 (in force for new models from 2025-08-02, transitional deadline
2027-08-02 for models already on the market, enforcement checks from
2026-08-02). It requires a **categorical summary of data sources and
modalities** -- it does NOT require raw training samples, full training
recipes, or model weights. This module fills in the template's structural
sections from real `ScanResult`/`RedactionResult` data (the PII/secrets
handling section) and leaves every section ReleaseGuard cannot verify (data
source licensing, third-party content, copyright status) as an explicit
placeholder. Never remove this scope note or soften it -- see
`CONTRIBUTING.md`'s section on compliance-template changes.
"""

from __future__ import annotations

from datetime import datetime, timezone

from releaseguard.types import RedactionResult, ScanResult

FILL_IN = "<!-- FILL IN: releaseguard cannot infer this from a scan alone -->"

TEMPLATE_REFERENCE_URL = (
    "https://digital-strategy.ec.europa.eu/en/policies/guidelines-training-data-summary"
)


def generate_eu_ai_act_summary(
    scan_result: ScanResult,
    redaction_result: RedactionResult | None = None,
    provider_name: str = FILL_IN,
    model_name: str = FILL_IN,
) -> str:
    """Return the Art. 53(1)(d) training-data-summary template as markdown.

    This is a starting document, not a filed compliance artifact -- a human
    must review and complete every `FILL_IN` placeholder, and this generator
    makes no claim that the resulting document satisfies Art. 53(1)(d) on
    its own. It only pre-populates what a real scan can verify.
    """
    entity_types = sorted(scan_result.entity_counts.keys())
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines: list[str] = []
    lines.append("# Training Data Summary (EU AI Act Art. 53(1)(d))")
    lines.append("")
    lines.append(
        f"_Draft generated by ReleaseGuard on {generated_at}. Based on the European "
        f"Commission's training-data-summary template "
        f"([reference]({TEMPLATE_REFERENCE_URL})), published 2025-07-24. "
        f"This covers the narrow, currently-binding categorical-summary "
        f"requirement only -- it is not a claim of full training-data disclosure._"
    )
    lines.append("")

    lines.append("## 1. Provider and Model Identification")
    lines.append("")
    lines.append(f"- **Provider:** {provider_name}")
    lines.append(f"- **Model name:** {model_name}")
    lines.append(f"- **Summary date:** {generated_at}")
    lines.append("")

    lines.append("## 2. Data Modalities and Approximate Size")
    lines.append("")
    lines.append(FILL_IN)
    lines.append("")

    lines.append("## 3. Data Sources")
    lines.append("")
    lines.append("| Source category | Description | Approximate share |")
    lines.append("| --- | --- | --- |")
    lines.append(f"| Publicly available datasets | {FILL_IN} | {FILL_IN} |")
    lines.append(f"| Licensed / proprietary data | {FILL_IN} | {FILL_IN} |")
    lines.append(f"| Web-scraped content | {FILL_IN} | {FILL_IN} |")
    lines.append(f"| User-generated / user-provided data | {FILL_IN} | {FILL_IN} |")
    lines.append(f"| Synthetic data | {FILL_IN} | {FILL_IN} |")
    lines.append("")

    lines.append("## 4. Personal Data and PII Handling (from ReleaseGuard scan)")
    lines.append("")
    lines.append(
        f"A Presidio-backed scan (detector: `{scan_result.detector_name}`) covered "
        f"{scan_result.files_scanned} file(s) under `{scan_result.root_path}`."
    )
    lines.append("")
    if entity_types:
        lines.append("| PII/secret category detected | Occurrences |")
        lines.append("| --- | --- |")
        for entity_type in entity_types:
            lines.append(f"| `{entity_type}` | {scan_result.entity_counts[entity_type]} |")
    else:
        lines.append("No PII/secret entities were detected at the configured score threshold.")
    lines.append("")
    if redaction_result is not None:
        total = sum(redaction_result.entities_redacted.values())
        lines.append(
            f"{total} detected entities were redacted (strategy: `{redaction_result.strategy}`) "
            f"prior to this summary being generated."
        )
    else:
        lines.append(
            "**No redaction has been applied yet.** Run `releaseguard redact` before "
            "publishing if the table above lists any findings."
        )
    lines.append("")

    lines.append("## 5. Copyright-Protected Content")
    lines.append("")
    lines.append(FILL_IN)
    lines.append("")

    lines.append("## 6. Update History")
    lines.append("")
    lines.append(
        "Art. 53(1)(d) requires this summary to be kept up to date at each "
        "material training update. Record each regeneration below."
    )
    lines.append("")
    lines.append("| Date | Change |")
    lines.append("| --- | --- |")
    lines.append(f"| {generated_at} | Initial draft generated by ReleaseGuard |")
    lines.append("")

    return "\n".join(lines)
