"""Generate a Hugging Face-format model card from real scan/redaction results.

Same non-fabrication discipline as `dataset_card.py`: only the scan/redaction
numbers ReleaseGuard actually measured are filled in; everything else is an
explicit placeholder.
"""

from __future__ import annotations

from datetime import datetime, timezone

import yaml

from releaseguard.types import RedactionResult, ScanResult

FILL_IN = "<!-- FILL IN: releaseguard cannot infer this -->"


def _yaml_frontmatter() -> str:
    metadata = {"license": FILL_IN, "tags": ["releaseguard-scanned"]}
    return "---\n" + yaml.safe_dump(metadata, sort_keys=False) + "---\n"


def generate_model_card(
    scan_result: ScanResult,
    redaction_result: RedactionResult | None = None,
    model_name: str = FILL_IN,
) -> str:
    """Return a Hugging Face model card as a markdown string.

    Model directories (checkpoint configs, tokenizer files, training logs)
    are scanned the same way as dataset directories -- credentials and
    accidental PII leakage into config/log files is a real, documented
    release-hygiene risk distinct from training-data content.
    """
    entity_types = sorted(scan_result.entity_counts.keys())
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines: list[str] = [_yaml_frontmatter(), ""]
    lines.append(f"# Model Card for {model_name}")
    lines.append("")
    lines.append(f"_Generated by ReleaseGuard on {generated_at} from an actual PII/secret scan._")
    lines.append("")

    lines.append("## Model Details")
    lines.append("")
    lines.append(FILL_IN)
    lines.append("")

    lines.append("## Training Data Summary")
    lines.append("")
    lines.append(
        "See the accompanying EU AI Act Art. 53(1)(d) training-data-summary "
        "template (`eu-ai-act-training-summary.md`) generated alongside this card."
    )
    lines.append("")

    lines.append("## Secrets and PII Scan (model directory)")
    lines.append("")
    lines.append(
        f"Scanned {scan_result.files_scanned} file(s) in the model directory "
        f"(checkpoints, configs, logs) with Presidio (detector: `{scan_result.detector_name}`)."
    )
    lines.append("")
    if entity_types:
        lines.append("| Entity type | Occurrences found |")
        lines.append("| --- | --- |")
        for entity_type in entity_types:
            lines.append(f"| `{entity_type}` | {scan_result.entity_counts[entity_type]} |")
    else:
        lines.append(
            "No PII/secret entities were detected by Presidio at the configured score threshold."
        )
    lines.append("")

    if redaction_result is not None:
        lines.append(
            f"This directory has been redacted (strategy: `{redaction_result.strategy}`) "
            f"before packaging."
        )
        lines.append("")

    lines.append("## Bias, Risks, and Limitations")
    lines.append("")
    lines.append(FILL_IN)
    lines.append("")

    lines.append("## Licensing Information")
    lines.append("")
    lines.append(FILL_IN)
    lines.append("")

    return "\n".join(lines)
